name: Java 11 Ubuntu-18.04

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run tests
        run: mvn test -Dtest=LiteClientParserTest,UtilsTest
      - name: Build with Maven
        run: mvn package -DskipTests
      - run: mkdir MyLocalTon && cp target/MyLocalTon.jar MyLocalTon
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: MyLocalTon
