name: Java 11 Ubuntu-18.04

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn package -DskipTests
      - run: mkdir staging && cp target/MyLocalTon.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging 
