name: Cross-platform build


on:
  workflow_dispatch:
  push:
    branches:
      - main
      - arm64-aarch64
      - test-release

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn package -DskipTests
      - name: Upload artifact
        run: mkdir MyLocalTon && cp target/MyLocalTon.jar MyLocalTon
      - uses: actions/upload-artifact@v2
        with:
          name: MyLocalTon
          path: MyLocalTon
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: true
